### ISSUE TITLE
gh-oauth.imsun.net 是用于?

### ISSUE THREAD

**Issue by xinshangshangxin** [imsun/gitment#22]
hi, 我从代码中看见了如下内容
```
http.post('https://gh-oauth.imsun.net', {
          code,
          client_id,
          client_secret,
        }, '')
```
[https://github.com/imsun/gitment/blob/master/src/gitment.js#L102-L106](https://github.com/imsun/gitment/blob/master/src/gitment.js#L102-L106)

请问这是用于做什么的? 有这部分源代码吗?

**Comment by xinshangshangxin** [comment]
从英文 README 看见了
https://github.com/imsun/gitment#why-does-gitment-send-a-request-to-gh-oauthimsunnet

**Comment by baifachuan** [comment]
原来的地址已经不可用了，我也折腾了很多次换来换去，现在我自己搞了个，使用方法：
修改gitment.browser.js文件的3416行将https://gh-oauth.imsun.net/替换成：https://baifachuan.com:8443/

该服务器代码在：https://github.com/imsun/gh-oauth-server，不会记录任何信息，我也是自己的博客使用：https:www.baifachuan.com，因为该服务器需要https，所以构建在自己的服务下，需要的可以使用。

update the gitment.browser.js file replace https://gh-oauth.imsun.net/ to https://baifachuan.com:8443/.
This service won't record or store anything. It only attaches a CORS header to that request and provides proxy. So that users can login in the frontend without any server-side implementation.
